get_something:
   path: /api/something
   methods: GET
   controller: App\UserInterface\Controller\DefaultController
send_something:
   path: /api/something
   methods: POST
   controller: App\UserInterface\Controller\SendSomethingController
